---
info:
  scm-url: "@scm.url@"
  build-url: "https://travis-ci.org/codecentric/spring-boot-admin"

logging:
  level:
    ROOT: info
  file:
    name: "target/boot-admin-sample-servlet.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    restart:
      enabled: true
    env:
      post:
        enabled: true
    health:
      show-details: ALWAYS

spring:
  application:
    name: spring-boot-admin-sample-servlet
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          service-host-type: HOST_NAME
          metadata:
            tags:
              environment: test
  jmx:
    enabled: true
  main:
    lazy-initialization: true
---
# tag::customization-external-views[]
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: "🚀"
            url: http://codecentric.de
            order: 2000
# end::customization-external-views[]
---
# tag::customization-view-settings[]
spring:
  boot:
    admin:
      ui:
        view-settings:
          - name: "journal"
            enabled: false
# end::customization-view-settings[]

